import { jsPDF } from 'jspdf';
import { CodeReview } from '@/types';

export const exportToPDF = (review: CodeReview) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - (margin * 2);
  let yPosition = margin;

  // Helper function to add text with wrapping
  const addText = (text: string, fontSize: number = 10, isBold: boolean = false) => {
    doc.setFontSize(fontSize);
    if (isBold) {
      doc.setFont('helvetica', 'bold');
    } else {
      doc.setFont('helvetica', 'normal');
    }

    const lines = doc.splitTextToSize(text, maxWidth);
    
    lines.forEach((line: string) => {
      if (yPosition > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
      }
      doc.text(line, margin, yPosition);
      yPosition += fontSize * 0.5;
    });
    
    yPosition += 5; // Add spacing after text block
  };

  // Helper function to add code block
  const addCodeBlock = (code: string) => {
    doc.setFontSize(9);
    doc.setFont('courier', 'normal');
    doc.setFillColor(240, 240, 240);
    
    const lines = code.split('\n');
    const codeHeight = lines.length * 4 + 10;
    
    if (yPosition + codeHeight > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
    }
    
    doc.rect(margin, yPosition, maxWidth, codeHeight, 'F');
    yPosition += 7;
    
    lines.forEach((line) => {
      if (yPosition > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
      }
      doc.text(line || ' ', margin + 5, yPosition);
      yPosition += 4;
    });
    
    yPosition += 10;
  };

  // Title
  doc.setFillColor(59, 130, 246); // Blue
  doc.rect(0, 0, pageWidth, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('AI Code Review Report', pageWidth / 2, 25, { align: 'center' });
  
  yPosition = 50;
  doc.setTextColor(0, 0, 0);

  // Metadata
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const date = new Date(review.timestamp).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
  doc.text(`Date: ${date}`, margin, yPosition);
  yPosition += 7;
  doc.text(`Language: ${review.language}`, margin, yPosition);
  yPosition += 7;
  doc.text(`Review Type: ${review.reviewType}`, margin, yPosition);
  yPosition += 15;

  // Original Code Section
  addText('Original Code', 14, true);
  addCodeBlock(review.code);

  // AI Review Section
  addText('AI Review', 14, true);
  
  // Process the AI response - remove markdown and format nicely
  const cleanResponse = review.aiResponse
    .replace(/#{1,6}\s/g, '') // Remove markdown headers
    .replace(/\*\*(.*?)\*\*/g, '$1') // Remove bold
    .replace(/\*(.*?)\*/g, '$1') // Remove italic
    .replace(/`{1,3}(.*?)`{1,3}/g, '$1') // Remove code backticks
    .replace(/\[([^\]]+)\]\([^\)]+\)/g, '$1'); // Remove links
  
  addText(cleanResponse, 10, false);

  // Footer on last page
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Generated by AI Code Review Assistant - Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  // Save the PDF
  const fileName = `code-review-${review.language}-${Date.now()}.pdf`;
  doc.save(fileName);
};